### ISSUE TITLE
No valid versions available for create-react-unity

### ISSUE THREAD

**Issue by SuperLufkin** [ReactUnity/core#10]
Like mentioned in another issue, the wizard inside Unity doesn't work for me, so I tried  `npm init react-unity `on project root as mentioned in the comments, but I get a `No valid versions available for create-react-unity` error.

**Comment by KurtGokhan** [comment]
That comment was outdated. New script is:

```
npm init @reactunity
```

**Comment by SuperLufkin** [comment]
Thanks for updating the command!

If you don't mind, it seems that I have a (new?) problem: when I install the unity package in my project, I now have an error `Library\PackageCache\com.reactunity.core@0.0.15\Runtime\Helpers\ResourcesHelper.cs(17,78): error CS1525: Invalid expression term '='` (repeats 4 times in the same file) and it seems that the ReactOS component and the ReactOS menu doesn't appear anymore. It worked on 0.0.14.

Thanks again!

**Comment by KurtGokhan** [comment]
@SuperLufkin  v15 is a very big update. I am not surprised there are new problems. 

Looks like your Unity version does not support the new C# features. What Unity version are you using? I tested in 2020.2 and 2021.1 and it works.

**Comment by KurtGokhan** [comment]
Closing as the initial issue was solved.
